"""empty message

Revision ID: 32010758e6ed
Revises: f9a66b998e7c
Create Date: 2021-08-08 21:07:40.159852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32010758e6ed'
down_revision = 'f9a66b998e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel', sa.Column('comics_appeared_in', sa.Integer(), nullable=True))
    op.add_column('marvel', sa.Column('super_power', sa.String(length=150), nullable=True))
    op.add_column('marvel', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('marvel', sa.Column('owner', sa.String(), nullable=False))
    op.drop_constraint('marvel_user_token_fkey', 'marvel', type_='foreignkey')
    op.create_foreign_key(None, 'marvel', 'user', ['owner'], ['token'])
    op.drop_column('marvel', 'camera_quality')
    op.drop_column('marvel', 'weight')
    op.drop_column('marvel', 'user_token')
    op.drop_column('marvel', 'price')
    op.drop_column('marvel', 'dimensions')
    op.drop_column('marvel', 'cost_of_prod')
    op.drop_column('marvel', 'series')
    op.drop_column('marvel', 'max_speed')
    op.drop_column('marvel', 'flight_time')
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.add_column('marvel', sa.Column('flight_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('max_speed', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('series', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('cost_of_prod', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('dimensions', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('marvel', sa.Column('weight', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('marvel', sa.Column('camera_quality', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'marvel', type_='foreignkey')
    op.create_foreign_key('marvel_user_token_fkey', 'marvel', 'user', ['user_token'], ['token'])
    op.drop_column('marvel', 'owner')
    op.drop_column('marvel', 'date_created')
    op.drop_column('marvel', 'super_power')
    op.drop_column('marvel', 'comics_appeared_in')
    # ### end Alembic commands ###
