"""empty message

Revision ID: 49f6ee0278d4
Revises: 32010758e6ed
Create Date: 2021-08-09 00:08:19.129884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f6ee0278d4'
down_revision = '32010758e6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel', sa.Column('user_token', sa.String(), nullable=False))
    op.drop_constraint('marvel_owner_fkey', 'marvel', type_='foreignkey')
    op.create_foreign_key(None, 'marvel', 'user', ['user_token'], ['token'])
    op.drop_column('marvel', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'marvel', type_='foreignkey')
    op.create_foreign_key('marvel_owner_fkey', 'marvel', 'user', ['owner'], ['token'])
    op.drop_column('marvel', 'user_token')
    # ### end Alembic commands ###
