"""empty message

Revision ID: a8a63a6c9578
Revises: 49f6ee0278d4
Create Date: 2021-08-09 04:07:16.551807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a63a6c9578'
down_revision = '49f6ee0278d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'marvel', ['name'])
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'marvel', type_='unique')
    # ### end Alembic commands ###
