"""empty message

Revision ID: d5f68dbd0e6c
Revises: a8a63a6c9578
Create Date: 2021-08-09 10:21:15.215898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f68dbd0e6c'
down_revision = 'a8a63a6c9578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('marvel_name_key', 'marvel', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('marvel_name_key', 'marvel', ['name'])
    # ### end Alembic commands ###
